general.import = ["~/.config/hydense/current/theme/alacritty.toml"]

# terminal.shell = "/usr/bin/zsh"

[env]
TERM = "xterm-256color"

[window]
decorations = "None"
startup_mode = "Maximized"
padding = { x = 5 }

[font]
normal.family = 'Iosevka Nerd Font'
size = 11.2

[mouse]
hide_when_typing = true
